version: '3.8'
services:
  # php webserver
  grpc-webserver:
    container_name: grpc-webserver
    image: nginx:latest
    restart: always
    tty: true
    ports: 
      - 8000:8000
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php-src:/grpc
    links:
      - grpc-php
  
  # client side
  grpc-php:
    container_name: grpc-php
    build: ./infra/grpc-php
    tty: true
    ports:
      - 9000:9000
    volumes:
      - ./infra/grpc-php/php.ini:/etc/php.ini

  # server side
  grpc-golang:
    container_name: grpc-golang
    build: ./infra/grpc-golang
    tty: true
    ports:
      - 1323:1323
    volumes:
      - ./go-src:/grpc