<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

namespace GPBMetadata;

class Sample
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7010a0c73616d706c652e70726f746f120673616d706c6522250a0d53616d706c655265717565737412140a0c72657175657374506172616d18012001280922250a0e53616d706c65526573706f6e736512130a0b726573706f6e73654d736718012001280932430a0653616d706c6512390a0653616d706c6512152e73616d706c652e53616d706c65526571756573741a162e73616d706c652e53616d706c65526573706f6e7365220042045a022e2f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

