<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

namespace Sample;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response body
 *
 * Generated from protobuf message <code>sample.SampleResponse</code>
 */
class SampleResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string responseMsg = 1;</code>
     */
    protected $responseMsg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $responseMsg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sample::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string responseMsg = 1;</code>
     * @return string
     */
    public function getResponseMsg()
    {
        return $this->responseMsg;
    }

    /**
     * Generated from protobuf field <code>string responseMsg = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setResponseMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->responseMsg = $var;

        return $this;
    }

}

