<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

namespace Sample;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request body
 *
 * Generated from protobuf message <code>sample.SampleRequest</code>
 */
class SampleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string requestParam = 1;</code>
     */
    protected $requestParam = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $requestParam
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sample::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string requestParam = 1;</code>
     * @return string
     */
    public function getRequestParam()
    {
        return $this->requestParam;
    }

    /**
     * Generated from protobuf field <code>string requestParam = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestParam = $var;

        return $this;
    }

}

